// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EventTypeController from "./event_type_controller"
application.register("event-type", EventTypeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PageTemplateController from "./page_template_controller"
application.register("page-template", PageTemplateController)

import ReportFormController from "./report_form_controller"
application.register("report-form", ReportFormController)
