// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import AskDisplayController from "controllers/ask_display_controller"
application.register("ask-display", AskDisplayController)

import AskFormController from "controllers/ask_form_controller"
application.register("ask-form", AskFormController)

import AskLiveController from "controllers/ask_live_controller"
application.register("ask-live", AskLiveController)

import EventTypeController from "controllers/event_type_controller"
application.register("event-type", EventTypeController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import PageTemplateController from "controllers/page_template_controller"
application.register("page-template", PageTemplateController)

import ReportFormController from "controllers/report_form_controller"
application.register("report-form", ReportFormController)
